---
title: "Transforming data about Brazilian Elections"
output: html_notebook
---


```{r}
library(tidyverse)
library(here)
```

# Percentagem de votos por eleição

```{r}
data <- read_csv(here::here("data/votos_tidy_long.csv"),
                 col_types = cols(
                      estado = col_character(),
                      candidato = col_character(),
                      votos = col_double(),
                      cargo = col_character(),
                      ano = col_integer(),
                      turno = col_character())) %>% 
        na.omit()

data%>% 
  glimpse()
```

```{r}
data %>%
  group_by(ano, turno) %>%
  summarize(votos_ano = sum(votos)) %>%
  ungroup() -> totais

totais %>% 
  sample_n(5)
```

```{r}
data %>%
  dplyr::full_join(totais, 
                   by=c("ano", "turno")) -> data

data %>%
  glimpse()
```

```{r}
data %>%
  group_by(ano,turno,
           candidato) %>%
  summarize(votos_candidato = sum(votos)) %>%
  ungroup() -> totais_candidatos

totais_candidatos %>% 
  sample_n(5)
```

```{r}
data %>%
  dplyr::full_join(totais_candidatos, 
                   by=c("ano", "turno",
                        "candidato")) -> data

data %>%
  glimpse()
```

```{r}
data %>%
  group_by(ano, turno, candidato) %>%
  mutate(perc_candidato = votos_candidato / votos_ano) -> temp
```

```{r}
temp %>%
  group_by(ano,turno, candidato) %>%
  slice(1) %>% 
  ungroup() %>%
  group_by(ano,turno) %>%
  top_n(2, perc_candidato) %>%
  ungroup() %>%
  select(ano,turno,
         candidato, 
         votos_ano, 
         votos_candidato,
         perc_candidato) -> max_perc_candidates
```

```{r}
max_perc_candidates %>%
  write_csv(here::here("data/perc_candidatos.csv"))
```

# Relação Estados


```{r}
estados <- read_csv(here::here("data/estados.csv"),
                    col_types = cols(
                      uf = col_character(),
                      estado = col_character()))

abstencoes <- read_csv(here::here("data/abstencoes_ano-a-ano.csv"),
                       col_types =  cols(
                         estado = col_character(),
                         ano = col_integer(),
                         turno = col_integer(),
                         situacao = col_character(),
                         quantidade = col_integer(),
                         proporcao = col_double()))
abstencoes %>% 
  dplyr::right_join(estados,
                   by = c("estado"))  -> abstencoes_estado

abstencoes_estado %>%
  write_csv(here::here("data/abstencoes_uf_ano.csv"))
```

